<?php
namespace Amazon\Region\EU;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-05-09 at 16:47:39.
 */
class West1Test extends \PHPUnit_Framework_TestCase
{
    /**
     * @var West1
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new West1;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Amazon\Region\AbstractRegion::isSESEnabled
     * @todo   Implement testIsSESEnabled().
     */
    public function testIsSESEnabled()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Amazon\Region\AbstractRegion::getSESHost
     * @todo   Implement testGetSESHost().
     */
    public function testGetSESHost()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
