<?php
namespace Amazon\Region\EU;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-05-09 at 16:47:39.
 */
class West1Test extends \PHPUnit_Framework_TestCase
{
    /**
     * @var West1
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new West1;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testIsSESEnabled()
    {
        $this->assertFalse($this->object->isSESEnabled());
    }

    public function testGetSESHost()
    {
        $this->setExpectedException('\RuntimeException');
        $this->object->getSESHost();
    }
}
