<?php
namespace Amazon\Region;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-05-09 at 16:47:39.
 */
class FactoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Factory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Factory;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testGetRegionEUWest1()
    {
        $region = $this->object->getRegion('eu-west-1');

        $this->assertInstanceOf('\Amazon\Region\EU\West1', $region);
    }

    public function testGetRegionUSEast1()
    {
        $region = $this->object->getRegion('us-east-1');

        $this->assertInstanceOf('\Amazon\Region\US\East1', $region);
    }

    public function testGetRegionUnknown()
    {
        $this->setExpectedException('\RuntimeException');
        $region = $this->object->getRegion('doesnt-exist-2');
    }
}
