<?php
namespace Amazon\SES;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-05-09 at 16:47:39.
 */
class MessageTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Message
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Message;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Amazon\SES\Message::addTo
     * @todo   Implement testAddTo().
     */
    public function testAddTo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Amazon\SES\Message::setTo
     * @todo   Implement testSetTo().
     */
    public function testSetTo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Amazon\SES\Message::getTo
     * @todo   Implement testGetTo().
     */
    public function testGetTo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Amazon\SES\Message::addCc
     * @todo   Implement testAddCc().
     */
    public function testAddCc()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Amazon\SES\Message::setCc
     * @todo   Implement testSetCc().
     */
    public function testSetCc()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Amazon\SES\Message::getCc
     * @todo   Implement testGetCc().
     */
    public function testGetCc()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Amazon\SES\Message::addBcc
     * @todo   Implement testAddBcc().
     */
    public function testAddBcc()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Amazon\SES\Message::setBcc
     * @todo   Implement testSetBcc().
     */
    public function testSetBcc()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Amazon\SES\Message::getBcc
     * @todo   Implement testGetBcc().
     */
    public function testGetBcc()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Amazon\SES\Message::addReplyTo
     * @todo   Implement testAddReplyTo().
     */
    public function testAddReplyTo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Amazon\SES\Message::setReplyTo
     * @todo   Implement testSetReplyTo().
     */
    public function testSetReplyTo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Amazon\SES\Message::getReplyTo
     * @todo   Implement testGetReplyTo().
     */
    public function testGetReplyTo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Amazon\SES\Message::setFrom
     * @todo   Implement testSetFrom().
     */
    public function testSetFrom()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Amazon\SES\Message::getFrom
     * @todo   Implement testGetFrom().
     */
    public function testGetFrom()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Amazon\SES\Message::setReturnPath
     * @todo   Implement testSetReturnPath().
     */
    public function testSetReturnPath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Amazon\SES\Message::getReturnPath
     * @todo   Implement testGetReturnPath().
     */
    public function testGetReturnPath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Amazon\SES\Message::hasReturnPath
     * @todo   Implement testHasReturnPath().
     */
    public function testHasReturnPath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Amazon\SES\Message::setSubject
     * @todo   Implement testSetSubject().
     */
    public function testSetSubject()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Amazon\SES\Message::getSubject
     * @todo   Implement testGetSubject().
     */
    public function testGetSubject()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Amazon\SES\Message::hasSubject
     * @todo   Implement testHasSubject().
     */
    public function testHasSubject()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Amazon\SES\Message::setBodyText
     * @todo   Implement testSetBodyText().
     */
    public function testSetBodyText()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Amazon\SES\Message::getBodyText
     * @todo   Implement testGetBodyText().
     */
    public function testGetBodyText()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Amazon\SES\Message::hasBodyText
     * @todo   Implement testHasBodyText().
     */
    public function testHasBodyText()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Amazon\SES\Message::setBodyHtml
     * @todo   Implement testSetBodyHtml().
     */
    public function testSetBodyHtml()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Amazon\SES\Message::getBodyHtml
     * @todo   Implement testGetBodyHtml().
     */
    public function testGetBodyHtml()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Amazon\SES\Message::hasBodyHtml
     * @todo   Implement testHasBodyHtml().
     */
    public function testHasBodyHtml()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Amazon\SES\Message::setCharsetSubject
     * @todo   Implement testSetCharsetSubject().
     */
    public function testSetCharsetSubject()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Amazon\SES\Message::getCharsetSubject
     * @todo   Implement testGetCharsetSubject().
     */
    public function testGetCharsetSubject()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Amazon\SES\Message::setCharsetBodyText
     * @todo   Implement testSetCharsetBodyText().
     */
    public function testSetCharsetBodyText()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Amazon\SES\Message::getCharsetBodyText
     * @todo   Implement testGetCharsetBodyText().
     */
    public function testGetCharsetBodyText()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Amazon\SES\Message::setCharsetBodyHtml
     * @todo   Implement testSetCharsetBodyHtml().
     */
    public function testSetCharsetBodyHtml()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Amazon\SES\Message::getCharsetBodyHtml
     * @todo   Implement testGetCharsetBodyHtml().
     */
    public function testGetCharsetBodyHtml()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Amazon\SES\Message::isValid
     * @todo   Implement testIsValid().
     */
    public function testIsValid()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
