<?php
namespace Amazon\Region\US;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-05-09 at 16:47:39.
 */
class East1Test extends \PHPUnit_Framework_TestCase
{
    /**
     * @var East1
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new East1;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Amazon\Region\US\East1::isSESEnabled
     * @todo   Implement testIsSESEnabled().
     */
    public function testIsSESEnabled()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Amazon\Region\US\East1::getSESHost
     * @todo   Implement testGetSESHost().
     */
    public function testGetSESHost()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
