<?php
namespace Amazon\Region\US;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-05-09 at 16:47:39.
 */
class East1Test extends \PHPUnit_Framework_TestCase
{
    /**
     * @var East1
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new East1;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testIsSESEnabled()
    {
        $this->assertTrue($this->object->isSESEnabled());
    }

    public function testGetSESHost()
    {
        $this->assertSame('email.us-east-1.amazonaws.com', $this->object->getSESHost());
    }
}
