<?php
namespace Amazon\Service;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-05-09 at 16:47:40.
 */
class SESTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var SES
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SES;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Amazon\Service\SES::authenticate
     * @todo   Implement testAuthenticate().
     */
    public function testAuthenticate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Amazon\Service\SES::listVerifiedEmailAddresses
     * @todo   Implement testListVerifiedEmailAddresses().
     */
    public function testListVerifiedEmailAddresses()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Amazon\Service\SES::verifyEmailAddress
     * @todo   Implement testVerifyEmailAddress().
     */
    public function testVerifyEmailAddress()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Amazon\Service\SES::deleteVerifiedEmailAddress
     * @todo   Implement testDeleteVerifiedEmailAddress().
     */
    public function testDeleteVerifiedEmailAddress()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Amazon\Service\SES::getSendQuota
     * @todo   Implement testGetSendQuota().
     */
    public function testGetSendQuota()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Amazon\Service\SES::getSendStatistics
     * @todo   Implement testGetSendStatistics().
     */
    public function testGetSendStatistics()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Amazon\Service\SES::sendEmail
     * @todo   Implement testSendEmail().
     */
    public function testSendEmail()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Amazon\Service\SES::setMultiParam
     * @todo   Implement testSetMultiParam().
     */
    public function testSetMultiParam()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
